fileVersion: 1
id: "37"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: BEN_EDW
    schema: DEV_SMOL_BOI_ENV
name: New Environment
type: Environment
