fileVersion: 1
id: "86"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: BEN_EDW
    schema: TRASH_ENV_UPDATE
name: New Environment
type: Environment
